{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2018-16880",
      "ASSIGNER": "secalert@redhat.com"
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-787"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16880",
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16880",
          "refsource": "CONFIRM",
          "tags": [
            "Issue Tracking",
            "Patch",
            "Third Party Advisory"
          ]
        },
        {
          "url": "http://www.securityfocus.com/bid/106735",
          "name": "106735",
          "refsource": "BID",
          "tags": [
            "Third Party Advisory",
            "VDB Entry"
          ]
        },
        {
          "url": "https://usn.ubuntu.com/3903-2/",
          "name": "USN-3903-2",
          "refsource": "UBUNTU",
          "tags": [
            "Third Party Advisory"
          ]
        },
        {
          "url": "https://usn.ubuntu.com/3903-1/",
          "name": "USN-3903-1",
          "refsource": "UBUNTU",
          "tags": [
            "Third Party Advisory"
          ]
        },
        {
          "url": "https://support.f5.com/csp/article/K03593314",
          "name": "https://support.f5.com/csp/article/K03593314",
          "refsource": "CONFIRM",
          "tags": [
            "Third Party Advisory"
          ]
        },
        {
          "url": "http://lists.opensuse.org/opensuse-security-announce/2019-05/msg00037.html",
          "name": "openSUSE-SU-2019:1404",
          "refsource": "SUSE",
          "tags": [
            "Mailing List",
            "Third Party Advisory"
          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A flaw was found in the Linux kernel's handle_rx() function in the [vhost_net] driver. A malicious virtual guest, under specific conditions, can trigger an out-of-bounds write in a kmalloc-8 slab on a virtual host which may lead to a kernel memory corruption and a system panic. Due to the nature of the flaw, privilege escalation cannot be fully ruled out. Versions from v4.16 and newer are vulnerable."
        }
      ]
    }
  },
  "configurations": {
    "nodes": [
      {
        "operator": "OR",
        "cpe_match": [
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:*"
          }
        ]
      },
      {
        "operator": "OR",
        "cpe_match": [
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:o:canonical:ubuntu_linux:18.04:*:*:*:lts:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:o:canonical:ubuntu_linux:18.10:*:*:*:*:*:*:*"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "vectorString": "AV:L/AC:M/Au:N/C:C/I:C/A:C",
        "accessVector": "LOCAL",
        "accessComplexity": "MEDIUM",
        "authentication": "NONE",
        "confidentialityImpact": "COMPLETE",
        "integrityImpact": "COMPLETE",
        "availabilityImpact": "COMPLETE",
        "baseScore": 6.9
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 3.4,
      "impactScore": 10,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2019-01-29T16:29Z",
  "lastModifiedDate": "2023-07-19T00:54Z"
}