{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2016-9391",
      "ASSIGNER": "cve@mitre.org"
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "NVD-CWE-Other"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "https://github.com/mdadams/jasper/commit/1e84674d95353c64e5c4c0e7232ae86fd6ea813b",
          "name": "https://github.com/mdadams/jasper/commit/1e84674d95353c64e5c4c0e7232ae86fd6ea813b",
          "refsource": "CONFIRM",
          "tags": [
            "Patch",
            "Third Party Advisory"
          ]
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1396967",
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1396967",
          "refsource": "CONFIRM",
          "tags": [
            "Issue Tracking",
            "Patch",
            "Third Party Advisory",
            "VDB Entry"
          ]
        },
        {
          "url": "https://blogs.gentoo.org/ago/2016/11/16/jasper-multiple-assertion-failure",
          "name": "https://blogs.gentoo.org/ago/2016/11/16/jasper-multiple-assertion-failure",
          "refsource": "MISC",
          "tags": [
            "Patch",
            "Third Party Advisory",
            "VDB Entry"
          ]
        },
        {
          "url": "http://www.securityfocus.com/bid/94371",
          "name": "94371",
          "refsource": "BID",
          "tags": [
            "Third Party Advisory",
            "VDB Entry"
          ]
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2016/11/17/1",
          "name": "[oss-security] 20161117 Re: jasper: multiple assertion failures",
          "refsource": "MLIST",
          "tags": [
            "Mailing List",
            "Patch",
            "VDB Entry"
          ]
        },
        {
          "url": "https://access.redhat.com/errata/RHSA-2017:1208",
          "name": "RHSA-2017:1208",
          "refsource": "REDHAT",
          "tags": []
        },
        {
          "url": "https://usn.ubuntu.com/3693-1/",
          "name": "USN-3693-1",
          "refsource": "UBUNTU",
          "tags": []
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "The jpc_bitstream_getbits function in jpc_bs.c in JasPer before 2.0.10 allows remote attackers to cause a denial of service (assertion failure) via a very large integer."
        }
      ]
    }
  },
  "configurations": {
    "nodes": [
      {
        "operator": "OR",
        "cpe_match": [
          {
            "vulnerable": true,
            "cpe23Uri": "cpe:2.3:a:jasper_project:jasper:*:*:*:*:*:*:*:*"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "vectorString": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 5
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 10,
      "impactScore": 2.9,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2017-03-23T18:59Z",
  "lastModifiedDate": "2018-06-29T01:29Z"
}